In [2]:
import math
import numpy as np

#
# C(N,3)*8
# N*(N-1)*(N-2)/6*8 = N*(N-1)*(N-2)/3*4 = M
#

M = 130000
N = int(math.pow(float(M)*3/4,1.0/3))+2
m = N*(N-1)*(N-2)/3*4 + N*(N-1)*2 + N
print N, m

48 142928


In [37]:
encoding = []

bits1 = [
    (-1,),
    (1,)
]

bits2 = [
    (-1,-1),
    (-1,1),
    (1,-1),
    (1,1)
]

def encoding2(N):
    rows = (N-1)*N*2
    encoding = np.zeros((rows, N), dtype=np.int8)
    k = 0
    for i in xrange(N-1):
        for j in xrange(i+1, N):
            for dx in xrange(4):
                encoding[k+dx, i] = bits2[dx][0]
                encoding[k+dx, j] = bits2[dx][1]
            k += 4
    return encoding
    

bits3 = [
    (-1,-1,-1),
    (-1,-1,1),
    (-1,1,-1),
    (-1,1,1),
    (1,-1,-1),
    (1,-1,1),
    (1,1,-1),
    (1,1,1)
]

for i in xrange(N):
            for dx in xrange(2):
                row = np.zeros((N,), dtype=np.int8)
                row[i] = bits1[dx][0]
                encoding.append(row)

for i in xrange(N-1):
    for j in xrange(i+1, N):
            for dx in xrange(4):
                row = np.zeros((N,), dtype=np.int8)
                row[i] = bits2[dx][0]
                row[j] = bits2[dx][1]
                encoding.append(row)

for i in xrange(N-2):
    for j in xrange(i+1, N-1):
        for k in xrange(j+1, N):
            for dx in xrange(8):
                row = np.zeros((N,), dtype=np.int8)
                row[i] = bits3[dx][0]
                row[j] = bits3[dx][1]
                row[k] = bits3[dx][2]
                encoding.append(row)


In [33]:
len(encoding)
for i, x in enumerate(encoding[:200]):
    print i, x

0 [-1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
1 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
2 [ 0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
3 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
4 [ 0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
5 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
6 [ 0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
7 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [38]:
print encoding2(4)

[[-1 -1  0  0]
 [-1  1  0  0]
 [ 1 -1  0  0]
 [ 1  1  0  0]
 [-1  0 -1  0]
 [-1  0  1  0]
 [ 1  0 -1  0]
 [ 1  0  1  0]
 [-1  0  0 -1]
 [-1  0  0  1]
 [ 1  0  0 -1]
 [ 1  0  0  1]
 [ 0 -1 -1  0]
 [ 0 -1  1  0]
 [ 0  1 -1  0]
 [ 0  1  1  0]
 [ 0 -1  0 -1]
 [ 0 -1  0  1]
 [ 0  1  0 -1]
 [ 0  1  0  1]
 [ 0  0 -1 -1]
 [ 0  0 -1  1]
 [ 0  0  1 -1]
 [ 0  0  1  1]]


In [3]:
import random

x=np.random.random((10,))
print x
random.shuffle(x)
print x

[ 0.22695811  0.4031782   0.28987042  0.57246881  0.35720753  0.92254369
  0.41240412  0.81057308  0.03013823  0.99796805]
[ 0.92254369  0.4031782   0.57246881  0.35720753  0.22695811  0.81057308
  0.03013823  0.28987042  0.99796805  0.41240412]
