In [1]:
import pandas as pd
import numpy as np

lst = [np.random.random((4,)) for _ in range(5)]
lst

[array([ 0.87992632,  0.0973243 ,  0.77573197,  0.98820688]),
 array([ 0.10583878,  0.4157038 ,  0.25556514,  0.847697  ]),
 array([ 0.51943242,  0.92732835,  0.18789242,  0.47821462]),
 array([ 0.03130225,  0.91170519,  0.82503654,  0.68131536]),
 array([ 0.63365105,  0.70758333,  0.74662303,  0.90580158])]

In [2]:
series = pd.Series(lst)
series

0    [0.879926323614, 0.097324304781, 0.77573197417...
1    [0.105838777111, 0.415703803564, 0.25556514358...
2    [0.519432416875, 0.927328345548, 0.18789241645...
3    [0.0313022488958, 0.911705189526, 0.8250365403...
4    [0.633651053862, 0.707583334048, 0.74662303020...
dtype: object

In [4]:
df=pd.DataFrame(series)
df.index=['a','b','c','d','e']
df

0
a  [0.879926323614, 0.097324304781, 0.77573197417...
b  [0.105838777111, 0.415703803564, 0.25556514358...
c  [0.519432416875, 0.927328345548, 0.18789241645...
d  [0.0313022488958, 0.911705189526, 0.8250365403...
e  [0.633651053862, 0.707583334048, 0.74662303020...